# Generated by Django 5.2.4 on 2025-08-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_options_alter_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
